# backend/Dockerfile

# Börja från den officiella PHP-bilden du använder
FROM docker.io/library/php:8.3-apache

# Installera mysqli och pdo_mysql (PDO driver)
RUN docker-php-ext-install mysqli pdo_mysql